### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by nikola-rados** [exmaple/underScore#1]
Some initial setup needs to be done to create the base discord bot before we can get specific.  There is a great [tutorial](https://www.youtube.com/watch?v=5yahh4tR0L0&list=PLW3GfRiBCHOiEkjvQj0uaUB1Q-RckYnj9) to help get started.  Goal of this issue is to get a bot running in a server off of a local machine.

**Comment by maxUser** [comment]
The same guy has an [updated version](https://www.youtube.com/watch?v=nW8c7vT6Hl4&t=93s) of the tutorial. Which one is more relevant?

**Comment by nikola-rados** [comment]
Let's go with the updated version.

**Comment by nikola-rados** [comment]
Just as another note @maxUser I think we should be using [python black](https://github.com/psf/black) to format our code.  Its a tool that very strictly formats code, I think it could be good to maintain consistency.

**Comment by nikola-rados** [comment]
All the initial code for this issue was written directly on the master branch.  This will be the baseline going forward as we develop the bot.
