### ISSUE TITLE
Commenting standards

### ISSUE THREAD

**Issue by maxUser** [exmaple/underScore#15]
We should adopt standardized commenting practices. I don't have any suggestions at the moment. I just had to get this written down. I'll look into it (although @nikola-rados probably already has a good idea of how we should comment).

**Comment by nikola-rados** [comment]
I think we should just try and ensure we have docstrings for each method. Maybe something similar to what is outlined in this [article](https://www.datacamp.com/community/tutorials/docstrings-python).
