### ISSUE TITLE
Data retrieval testing

### ISSUE THREAD

**Issue by maxUser** [exmaple/underScore#16]
We need to add test cases for data retrieval and validation.

**Comment by maxUser** [comment]
@nikola-rados should we just delete this? I think the real testing we need is to make sure the commands run. While working on the `!matchday` command, the command would break after making changes mostly because of syntax or logic errors. Can we write a test for each command to make sure they still run?

**Comment by nikola-rados** [comment]
I think the idea behind this issue is that it would check the commands as well as some of the util functions we’ve made. I feel like it’s still valid.

**Comment by maxUser** [comment]
Okay sounds good. We should talk about this in the near future then. I have some questions.
