### ISSUE TITLE
Default outputs for getMatchday

### ISSUE THREAD

**Issue by nikola-rados** [exmaple/underScore#28]
Currently `getMatchday` requires two arguments (`matchday`, `season`).  We would like the command to be a bit more flexible and allow for several combinations.  If the command is called with no arguments, the most recent matchday is returned.  If the command is called with a `matchday` the most recent occurrence of that matday is returned.

**Comment by maxUser** [comment]
made branch: i28-matchday-defaults

**Comment by nikola-rados** [comment]
After reading this in the docstring:

"The URL of this website uses only the latter year in a season (2019/2020).  `season[5:9]` selects the latter season." 

And actually understanding the context of what it means, I think we could probably just pass a single year into the command.  Rather than take the last year from `2019/2020` we could probably just increment the year for the website.  

What're you thoughts?
