### ISSUE TITLE
Help page

### ISSUE THREAD

**Issue by nikola-rados** [exmaple/underScore#29]
By default a `!help` command is available.  We would like to expand on this command to get specific help for commands using `!help [command]`.

**Comment by maxUser** [comment]
This is built-in functionality, hurray!

**Comment by maxUser** [comment]
It's too damn ugly, we gotta customize it!

**Comment by maxUser** [comment]
FYI
https://discordpy.readthedocs.io/en/latest/ext/commands/api.html?highlight=command#discord.ext.commands.HelpCommand.command_attrs
